apiVersion: v1
kind: PersistentVolume
metadata:
  name: noi-gluster-pv
spec:
  capacity:
    storage: 500Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: icp-gluster-glusterfs-heketi-service
    path: icp
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
